import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mapRelease} from '../src/domain/material-release/mapping.js';
import {packMapped,payloadWithinLimits} from '../src/domain/material-release/packing.js';
import {validateImport} from '../src/domain/content-library.js';
import {makeRelease,makeQuestion,makeNote,refreshRelease} from './helpers/material-release.js';
function batch(count){const r=makeRelease();r.records.questions=Array.from({length:count},(_,i)=>makeQuestion('test-q'+String(i).padStart(4,'0')));r.manifest.eligibility.includedIds=r.records.questions.map(q=>q.recordId);return refreshRelease(r);}
function addNotes(r,count){r.records.notes=Array.from({length:count},(_,i)=>makeNote('test-n'+i));r.records.relations=r.records.notes.flatMap(n=>r.records.questions.map(q=>({relationId:n.recordId+'-'+q.recordId,kind:'explains',fromId:n.recordId,toId:q.recordId,section:''})));r.manifest.eligibility.includedIds.push(...r.records.notes.map(n=>n.recordId));return refreshRelease(r);}
test('repeat_run_identical',()=>{const m=mapRelease(batch(101));const shuffled=structuredClone(m);shuffled.questions.reverse();const a=packMapped(m),b=packMapped(shuffled);assert.deepEqual(a,b);assert.deepEqual(a.chunks[0].manifest.questions[0].options,[{optionId:'first',text:'Circle'},{optionId:'second',text:'Square'}]);const changed=structuredClone(m);changed.adapterVersion='2';assert.notEqual(packMapped(changed).chunks[0].importId,a.chunks[0].importId);});
test('limits_100_101_questions',()=>{assert.deepEqual(packMapped(mapRelease(batch(100))).chunks.map(c=>c.manifest.questions.length),[100]);assert.deepEqual(packMapped(mapRelease(batch(101))).chunks.map(c=>c.manifest.questions.length),[100,1]);});
test('limits_100_101_notes',()=>{assert.equal(packMapped(mapRelease(addNotes(batch(1),100))).chunks[0].manifest.notes.length,100);const tooBig=packMapped(mapRelease(addNotes(batch(1),101)));assert.equal(tooBig.chunks.length,0);assert.ok(tooBig.diagnostics.some(d=>d.code==='component_too_large'));});
for(const [kind,idKey] of [['concepts','conceptId'],['sources','sourceId']])test('limits_200_201_'+kind,()=>{const r=batch(101),sample=r.records[kind][0];r.records[kind]=Array.from({length:201},(_,i)=>{const x=structuredClone(sample);x.recordId='test-'+kind+'-'+i;x.app[idKey]=x.recordId;if(x.contentFile)x.contentFile='content/'+x.recordId+'.md';return x;});r.records.questions.forEach((q,i)=>{const ids=r.records[kind].slice(i*2,i*2+2).map(x=>x.recordId);if(kind==='concepts')q.app.conceptLinks=ids.map((conceptId,j)=>({conceptId,role:j===0?'primary':'secondary'}));else {q.app.sourceIds=ids;q.archive.gates.forEach(g=>{if(g.evidenceRefs.length)g.evidenceRefs[0].sourceId=ids[0];});}});refreshRelease(r);const m=packMapped(mapRelease(r));assert.ok(m.chunks.length>=2);assert.ok(m.chunks.every(c=>c.manifest[kind].length<=200));});
test('limits_500_501_links',()=>{const r=addNotes(batch(5),100);assert.equal(packMapped(mapRelease(r)).chunks[0].manifest.noteQuestionLinks.length,500);const q=makeQuestion('extra-q');r.records.questions.push(q);r.records.relations.push({relationId:'extra-link',kind:'explains',fromId:r.records.notes[0].recordId,toId:q.recordId,section:''});r.manifest.eligibility.includedIds.push(q.recordId);refreshRelease(r);const h=packMapped(mapRelease(r));assert.equal(h.chunks.length,0);assert.ok(h.diagnostics.some(d=>d.code==='component_too_large'));});
test('exact_utf8_1mib',()=>{const m={schemaVersion:1,importId:'test',concepts:[],sources:[],questions:[],notes:[],noteQuestionLinks:[],padding:''};const size=Buffer.byteLength(JSON.stringify(m,null,2)+'\n');m.padding='x'.repeat(1048576-size-2)+'é';assert.equal(Buffer.byteLength(JSON.stringify(m,null,2)+'\n'),1048576);assert.equal(payloadWithinLimits(m),true);m.padding+='x';assert.equal(payloadWithinLimits(m),false);});
test('linked_note_questions_stay_complete',()=>{const h=packMapped(mapRelease(addNotes(batch(2),1)));assert.equal(h.chunks.length,1);const m=h.chunks[0].manifest;assert.equal(m.questions.length,2);assert.equal(m.notes.length,1);assert.equal(m.noteQuestionLinks.length,2);assert.doesNotThrow(()=>validateImport(m));assert.equal(createHash('sha256').update(h.chunks[0].bytes).digest('hex'),h.chunks[0].sha256);});
test('dependent_source_conflict_across_chunks',()=>{const m=mapRelease(batch(101));m.sources.push({...m.sources[0],title:'conflicting'});assert.throws(()=>packMapped(m),/dependency_identity_conflict/);});
test('unsupported_empty_import',()=>{const m=mapRelease(makeRelease());m.questions=[];const h=packMapped(m);assert.equal(h.chunks.length,0);assert.ok(h.diagnostics.some(d=>d.code==='empty_eligible_import'));});
