import test from 'node:test';
import assert from 'node:assert/strict';
import {appendQuestionVersion} from '../src/domain/content.js';
import {mapRelease} from '../src/domain/material-release/mapping.js';
import {buildCorrectionProposals,assertProposalBase} from '../src/domain/material-release/corrections.js';
import {makeRelease,targetFor,refreshRelease} from './helpers/material-release.js';
function setup(){const r=makeRelease(),t=targetFor(r);r.records.questions[0].app.explanation+=' Updated artificial explanation.';refreshRelease(r);return {r,t};}
function proposal(r,t){return buildCorrectionProposals(r,mapRelease(r,{target:t}),t)[0];}
test('correction_retains_id',()=>{const {r,t}=setup(),p=proposal(r,t);assert.equal(p.questionId,'test-q');assert.equal(p.expectedQuestionVersionId,'test-q@1');assert.equal(p.status,'correction_delivery_blocked');assert.equal(p.proposedContent.explanation,r.records.questions[0].app.explanation);assert.ok(p.evidence.length);});
test('answer_conflict_requires_review',()=>{const {r,t}=setup();r.records.questions[0].app.answerOptionId='second';refreshRelease(r);const p=proposal(r,t);assert.equal(p.questionId,'test-q');assert.ok(p.requiredGates.includes('disputed-key-review'));assert.equal(p.status,'correction_delivery_blocked');});
test('provenance_only',()=>{const r=makeRelease(),t=targetFor(r);t.questionMetadata[0].origins=[{kind:'platform',platformId:'test-other'}];const p=proposal(r,t);assert.equal(p.kind,'provenance');assert.equal(p.proposedContent.stem,t.catalog.questions[0].stem);assert.equal(p.proposedContent.answerOptionId,t.catalog.questions[0].answerOptionId);});
test('stale_base_rejected',()=>{const {r,t}=setup(),p=proposal(r,t),changed=structuredClone(t);changed.catalog.questions[0].stem+=' Changed';assert.throws(()=>assertProposalBase(p,changed),/stale_question_version/);changed.catalog.questions[0].questionVersionId='test-q@2';assert.throws(()=>assertProposalBase(p,changed),/stale_question_version/);assert.doesNotThrow(()=>assertProposalBase(p,t));});
test('corrected_source_new_identity',()=>{const {r,t}=setup();r.records.sources[0].recordId='test-source-new';r.records.sources[0].app.sourceId='test-source-new';r.records.sources[0].app.version='test-v2';r.records.questions[0].app.sourceIds=['test-source-new'];r.records.questions[0].archive.gates.forEach(g=>g.evidenceRefs.forEach(e=>e.sourceId='test-source-new'));refreshRelease(r);const p=proposal(r,t);assert.deepEqual(p.proposedContent.sourceIds,['test-source-new']);assert.equal(t.catalog.sources[0].sourceId,'test-source');});
test('historic_catalog_unchanged and derivatives_not_rebound',()=>{const {r,t}=setup();t.questionMetadata[0].intelligence={derivatives:[{variantId:'test-variant',sourceQuestionVersionId:'test-q@1'}]};const before=JSON.stringify(t),p=proposal(r,t);assert.deepEqual(p.affectedDerivativeIds,['test-variant']);assert.equal(JSON.stringify(t),before);const old=t.catalog.questions[0],draft={...old,...p.proposedContent,questionVersionId:'test-q@2',version:2,supersedes:'test-q@1',authorId:'test-author-2',changeReason:p.changeReason,status:'draft',reviews:[],publishedAt:null};delete draft.origins;delete draft.classification;delete draft.intelligence;const next=appendQuestionVersion(t.catalog,draft);assert.deepEqual(next.questions[0],old);assert.deepEqual(next.questions[1].reviews,[]);assert.equal(next.questions[1].publishedAt,null);assert.equal(JSON.stringify(t),before);});
test('different_task_requires_identity_review and no target is not guessed',()=>{const {r,t}=setup();r.records.questions[0].app.stem='A wholly different artificial task.';refreshRelease(r);assert.ok(proposal(r,t).requiredGates.includes('identity-review'));const p=buildCorrectionProposals(r,{releaseDigest:'x',routes:[{recordId:'test-q',kind:'correction'}]},null)[0];assert.equal(p.expectedQuestionVersionId,null);assert.equal(p.status,'conflict');});
