import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {inspectImageFile} from '../scripts/lib/material-media-files.js';
import {prepareMediaPackage,mediaBindingDigest} from '../src/domain/material-release/media-package.js';
import {toLearnerMediaPrompt} from '../src/domain/media.js';
import {mediaFixture,artificialImages} from './helpers/material-media.js';
async function facts(t,bytes){const dir=await mkdtemp(join(tmpdir(),'mlos-img-'));t.after(()=>rm(dir,{recursive:true,force:true}));const p=join(dir,'image');await writeFile(p,bytes);return inspectImageFile(p);}
async function setup(t){const x=mediaFixture();x.assetFacts={[x.path]:await facts(t,x.bytes)};return x;}
const prepare=x=>prepareMediaPackage(x.release,{target:x.target,assetFacts:x.assetFacts,privacyEvidence:x.release.assetsManifest.privacyEvidence});
test('actual image signatures and dimensions; corrupt and fake images rejected',async t=>{for(const fmt of ['png','jpeg','webp']){const f=await facts(t,Buffer.from(artificialImages[fmt],'base64'));assert.equal(f.mimeType,`image/${fmt}`);assert.equal(f.width,2);assert.equal(f.height,3);}await assert.rejects(()=>facts(t,Buffer.from('fake .png')),/invalid_image_bytes/);await assert.rejects(()=>facts(t,Buffer.from(artificialImages.png,'base64').subarray(0,25)),/invalid_image_bytes/);});
test('missing_asset_blocks and declarations cannot impersonate inspection',async t=>{const x=await setup(t);x.assetFacts={};assert.throws(()=>prepare(x),/missing_media_asset/);x.assetFacts={[x.path]:{mimeType:'image/png',width:2,height:3,sha256:x.bundle.assets[0].contentSha256,bytes:x.bytes.length}};assert.throws(()=>prepare(x),/unmeasured_media_asset/);});
test('byte_hash_mismatch actual_mime_mismatch declared_dimensions_mismatch',async t=>{for(const [field,value,code] of [['contentSha256','0'.repeat(64),'file_hash_mismatch'],['mimeType','image/jpeg','media_mime_mismatch'],['width',3,'media_dimensions_mismatch']]){const x=await setup(t);x.bundle.assets[0][field]=value;assert.throws(()=>prepare(x),new RegExp(code));}});
test('metadata_privacy_pending and unknown_rights_blocks',async t=>{const x=await setup(t);x.release.assetsManifest.privacyEvidence=[];assert.ok(prepare(x).diagnostics.includes('privacy_review_required'));x.bundle.assets[0].source.rightsStatus='unknown';assert.ok(prepare(x).diagnostics.includes('media_rights_unresolved'));assert.equal(prepare(x).status,'media_delivery_blocked');});
test('missing_predecessor_blocks',async t=>{const x=await setup(t);Object.assign(x.bundle.assets[0],{version:2,mediaAssetVersionId:'test-image@2',supersedes:'test-image@1'});assert.throws(()=>prepare(x),/invalid_media_bundle/);});
test('changed_asset_changes_binding including annotations and question',async t=>{const x=await setup(t),q=x.target.catalog.questions[0],privacy=x.release.assetsManifest.privacyEvidence,h=mediaBindingDigest(q,x.bundle,privacy);x.bundle.annotations[0].geometry.x=0.4;assert.notEqual(mediaBindingDigest(q,x.bundle,privacy),h);assert.notEqual(mediaBindingDigest({...q,explanation:q.explanation+' New'},mediaFixture().bundle,privacy),h);});
test('prompt_projection_no_evidence_or_annotations and leakage needs human binding evidence',async t=>{const x=await setup(t),prompt=toLearnerMediaPrompt(x.bundle,'test-q@1')[0];assert.deepEqual(Object.keys(prompt).sort(),['mediaAssetVersionId','modality','mimeType','width','height','deliveryRef','blindFirstLook'].sort());assert.ok(prepare(x).diagnostics.includes('prompt_leakage_review_required'));x.bundle.assets[0].deliveryRef='https://example.invalid/answer-circle.png';assert.throws(()=>prepare(x),/unsafe_media_delivery_reference/);});
test('new questions binding_pending and new objects cannot inherit asset review',async t=>{const x=await setup(t);x.target=null;assert.ok(prepare(x).diagnostics.includes('binding_pending'));x.bundle.assets[0].review={status:'gold_standard',reviewerId:'test-reviewer',reviewedAt:'2026-10-08T00:00:00.000Z'};assert.ok(prepare(x).diagnostics.includes('unverified_review_evidence'));});
