import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {archiveHandoff,stageTextHandoff,appendReleaseIndex} from '../src/adapters/material-release-delivery.js';
import {handoffDigest} from '../src/domain/material-release/receipts.js';
import {digestBytes,stableJson} from '../src/domain/material-release/packing.js';
import {makeTarget} from './helpers/material-release.js';
import {deliveryFixture,fakeArchive,fakeStage,clock} from './helpers/material-delivery.js';
function fakeIndex(){let document={entries:[],latestPortable:null,latestCompatible:null,latestStaged:null,latestPublished:{releaseId:'previous-published'},learnerRecords:['test-history']},version=1,calls=0;return {fixture:true,read:async()=>({version,document:structuredClone(document)}),compareAndAppend:async(expected,entry)=>{calls++;if(expected!==version)return {conflict:true};document.entries.push(entry);for(const k of ['latestPortable','latestCompatible','latestStaged','latestPublished'])if(entry.pointers[k])document[k]=entry.pointers[k];return {version:++version};},get document(){return structuredClone(document);},get calls(){return calls;}};}
async function setup(t){const x=await deliveryFixture(t),f=fakeArchive(),archiveReceipt=await archiveHandoff(x.handoff,{...x.args,...f});return {...x,f,archiveReceipt};}
test('archive_failed_does_not_move_pointer',async()=>{const p=fakeIndex();assert.deepEqual(await appendReleaseIndex({archiveReceipt:{state:'persistence_pending'}},p),{updated:false,conflict:false});assert.equal(p.calls,0);});
test('successful_archive_moves_only_portable and repeated_receipt_is_noop',async t=>{const {archiveReceipt}=await setup(t),p=fakeIndex();assert.deepEqual(await appendReleaseIndex({archiveReceipt},p),{updated:true,conflict:false});assert.equal(p.document.latestPortable.releaseId,archiveReceipt.releaseId);assert.equal(p.document.latestCompatible,null);assert.equal(p.document.latestStaged,null);assert.deepEqual(p.document.latestPublished,{releaseId:'previous-published'});assert.deepEqual(await appendReleaseIndex({archiveReceipt},p),{updated:false,conflict:false});assert.equal(p.calls,1);});
test('index_version_conflict_preserves_other_writer and no retry',async t=>{const {archiveReceipt}=await setup(t),p=fakeIndex();let calls=0;p.compareAndAppend=async()=>{calls++;return {conflict:true};};assert.deepEqual(await appendReleaseIndex({archiveReceipt},p),{updated:false,conflict:true});assert.equal(calls,1);assert.equal(p.document.entries.length,0);});
test('missing_saved_receipt_reference_blocks and tampered receipt is rejected',async t=>{const {archiveReceipt}=await setup(t),p=fakeIndex(),a=structuredClone(archiveReceipt);a.receiptReference=null;assert.deepEqual(await appendReleaseIndex({archiveReceipt:a},p),{updated:false,conflict:false});a.receiptReference=archiveReceipt.receiptReference;a.handoffDigest='c'.repeat(64);assert.deepEqual(await appendReleaseIndex({archiveReceipt:a},p),{updated:false,conflict:false});assert.equal(p.calls,0);});
test('fake end-to-end staged_does_not_move_published and learner/source bytes unchanged',async t=>{const x=await setup(t),original=await readFile(join(x.args.releaseDirectory,'manifest.json')),targetSnapshot=makeTarget(),s=fakeStage(),authorization={approvedReleaseId:x.handoff.releaseId,targetEnvironment:'isolated-test',mode:'isolated-test',preflightEvidence:{kind:'authorized-stage-validation',releaseId:x.handoff.releaseId,handoffDigest:handoffDigest(x.handoff),targetEnvironment:'isolated-test',targetSnapshotDigest:digestBytes(stableJson(targetSnapshot))}};const d=await stageTextHandoff(x.handoff,{archiveReceipt:x.archiveReceipt,targetSnapshot,port:s.port,journal:x.f.journal,authorization,clock}),p=fakeIndex();assert.deepEqual(await appendReleaseIndex({archiveReceipt:x.archiveReceipt,deliveryReceipt:d},p),{updated:true,conflict:false});assert.equal(p.document.latestStaged.releaseId,x.handoff.releaseId);assert.equal(p.document.latestCompatible,null);assert.deepEqual(p.document.latestPublished,{releaseId:'previous-published'});assert.deepEqual(p.document.learnerRecords,['test-history']);assert.deepEqual(await readFile(join(x.args.releaseDirectory,'manifest.json')),original);});
test('unknown index outcome reconciles readback rather than blindly retrying',async t=>{const {archiveReceipt}=await setup(t),p=fakeIndex(),write=p.compareAndAppend;p.compareAndAppend=async(...args)=>{await write(...args);throw Error('timeout');};assert.deepEqual(await appendReleaseIndex({archiveReceipt},p),{updated:true,conflict:false});assert.equal(p.calls,1);});
test('fixture evidence cannot update a production index',async t=>{const {archiveReceipt}=await setup(t),p=fakeIndex();p.fixture=false;assert.deepEqual(await appendReleaseIndex({archiveReceipt},p),{updated:false,conflict:false});assert.equal(p.calls,0);});
