import test from 'node:test';
import assert from 'node:assert/strict';
import {archiveHandoff,stageTextHandoff,prepareRepositoryHandoff} from '../src/adapters/material-release-delivery.js';
import {handoffDigest} from '../src/domain/material-release/receipts.js';
import {digestBytes,stableJson} from '../src/domain/material-release/packing.js';
import {makeTarget,makeRelease,makeQuestion,refreshRelease} from './helpers/material-release.js';
import {deliveryFixture,fakeArchive,fakeStage,clock} from './helpers/material-delivery.js';
async function setup(t,release){const x=await deliveryFixture(t,release),a=fakeArchive(),archiveReceipt=await archiveHandoff(x.handoff,{...x.args,...a}),targetSnapshot=makeTarget(),s=fakeStage(),authorization={approvedReleaseId:x.handoff.releaseId,targetEnvironment:'isolated-test',mode:'isolated-test',preflightEvidence:{kind:'authorized-stage-validation',releaseId:x.handoff.releaseId,handoffDigest:handoffDigest(x.handoff),targetEnvironment:'isolated-test',targetSnapshotDigest:digestBytes(stableJson(targetSnapshot))}};return {...x,a,s,options:{archiveReceipt,targetSnapshot,authorization,port:s.port,journal:a.journal,clock}};}
test('pending_archive_zero_stage_calls and missing_authorization_zero_stage_calls',async t=>{const x=await setup(t);for(const extra of [{archiveReceipt:{state:'persistence_pending'}},{authorization:null}]){assert.equal((await stageTextHandoff(x.handoff,{...x.options,...extra})).state,'delivery_blocked');assert.equal(x.s.stages,0);}});
test('fixture_receipt_rejected for live target',async t=>{const x=await setup(t);x.options.authorization.mode='live-active-task';const r=await stageTextHandoff(x.handoff,x.options);assert.equal(r.state,'delivery_blocked');assert.equal(x.s.stages,0);});
test('stale_target_requires_preflight rather than an age threshold',async t=>{const x=await setup(t);x.options.targetSnapshot.capturedAt='2026-10-07T00:00:00.000Z';const r=await stageTextHandoff(x.handoff,x.options);assert.equal(r.compatibility,'compatibility_pending');assert.equal(x.s.stages,0);});
test('draft_ack_receipt and server_digest_differs_from_file_hash',async t=>{const x=await setup(t),r=await stageTextHandoff(x.handoff,x.options);assert.equal(r.state,'staged');assert.equal(r.items[0].status,'staged');assert.equal(r.items[0].targetDigest,'a'.repeat(64));assert.notEqual(r.items[0].payloadSha256,r.items[0].targetDigest);assert.equal(r.persistence,'saved');assert.equal(JSON.stringify(r).includes('questionVersionId'),false);});
test('mismatched_remote_manifest blocks even when ID agrees',async t=>{const x=await setup(t),m=x.handoff.chunks[0].manifest;x.s.imports.set(m.importId,{import_id:m.importId,manifest:{...m,notes:[{}]},digest:'a'.repeat(64),status:'staged',receipt:null});const r=await stageTextHandoff(x.handoff,x.options);assert.equal(r.state,'delivery_blocked');assert.equal(x.s.stages,0);});
test('retry_reads_before_post reuses identical draft',async t=>{const x=await setup(t),a=await stageTextHandoff(x.handoff,x.options),b=await stageTextHandoff(x.handoff,{...x.options,priorReceipt:a});assert.equal(a.state,'staged');assert.equal(b.state,'staged');assert.equal(x.s.stages,1);});
test('post_timeout_then_reconcile has no automatic blind retry',async t=>{const x=await setup(t),stage=x.s.port.stage;x.s.port.stage=async m=>{await stage(m);throw Error('Bearer private-token');};const a=await stageTextHandoff(x.handoff,x.options);assert.equal(a.state,'reconciliation_required');assert.equal(x.s.stages,1);const b=await stageTextHandoff(x.handoff,{...x.options,priorReceipt:a});assert.equal(b.state,'staged');assert.equal(x.s.stages,1);assert.equal(JSON.stringify(a).includes('private-token'),false);});
test('remote_already_published requires actual publication receipt',async t=>{const x=await setup(t),m=x.handoff.chunks[0].manifest,d='b'.repeat(64),detail={import_id:m.importId,manifest:m,digest:d,status:'published',receipt:{contractId:'content-library-publication-v1',importId:m.importId,digest:d,status:'published',publishedAt:clock()}};x.s.imports.set(m.importId,detail);const r=await stageTextHandoff(x.handoff,x.options);assert.equal(r.items[0].status,'already_published');assert.equal(x.s.stages,0);detail.receipt=null;assert.equal((await stageTextHandoff(x.handoff,x.options)).state,'delivery_blocked');});
test('partial_batch retains first stage without cross-service rollback',async t=>{const r=makeRelease();r.records.questions=Array.from({length:101},(_,i)=>makeQuestion('test-q-'+i));r.manifest.eligibility.includedIds=r.records.questions.map(q=>q.recordId);refreshRelease(r);const x=await setup(t,r),stage=x.s.port.stage;let count=0;x.s.port.stage=async m=>{if(++count===2)throw Error('failed');return stage(m);};const receipt=await stageTextHandoff(x.handoff,x.options);assert.equal(receipt.state,'partially_staged');assert.equal(receipt.items[0].status,'staged');assert.equal(receipt.items[1].status,'reconciliation_required');});
test('publish_route_unreachable and malformed authority rejected',async t=>{const x=await setup(t),stage=x.s.port.stage;x.s.port.publish=()=>assert.fail('publish called');x.s.port.rightsDecision=()=>assert.fail('rights callback called');x.s.port.stage=async m=>({...await stage(m),publicationAuthority:true});assert.equal((await stageTextHandoff(x.handoff,x.options)).state,'delivery_blocked');});
test('receipt save failure retains actual stage and repository handoff stays pending',async t=>{const x=await setup(t);x.options.journal={append:async()=>{throw Error('save failed');}};const r=await stageTextHandoff(x.handoff,x.options);assert.equal(r.state,'staged');assert.equal(r.persistence,'receipt_persistence_pending');assert.equal(r.receiptReference,null);const repo=prepareRepositoryHandoff(x.handoff,x.options);assert.equal(repo.state,'repository_handoff_pending');assert.equal(repo.files[0].bytes,x.handoff.chunks[0].bytes);assert.ok(repo.files[0].path.startsWith('content/inbox/'));});
