import test from 'node:test';
import assert from 'node:assert/strict';
import {mapRelease} from '../src/domain/material-release/mapping.js';
import {packMapped} from '../src/domain/material-release/packing.js';
import {validateIntelligence} from '../src/domain/question-intelligence.js';
import {validateCatalog} from '../src/domain/content.js';
import {archiveHandoff} from '../src/adapters/material-release-delivery.js';
import {validateArchiveReceipt} from '../src/domain/material-release/receipts.js';
import {makeRelease,makeQuestion,makeNote,refreshRelease,targetFor} from './helpers/material-release.js';
import {deliveryFixture,fakeArchive} from './helpers/material-delivery.js';
const origin=()=>({kind:'pyq',examId:'test-exam',year:2025,session:'test-session',evidence:'Artificial occurrence'});
function addOccurrence(r,key='first',sourceId='test-source'){const o=origin();r.records.questions[0].app.origins=[o];r.records.occurrences=[{occurrenceId:'test-occ',questionId:'test-q',sourceId,locator:'synthetic-only',verification:'verified',origin:o,historicalKey:key}];return refreshRelease(r);}
test('review1 differing historical keys cannot become verified app origins',()=>{const r=addOccurrence(makeRelease(),'second'),m=mapRelease(r);assert.equal(m.questions.length,0);assert.ok(m.excluded.some(x=>x.reason==='historical_key_conflict'));assert.equal(r.records.occurrences[0].historicalKey,'second');r.records.occurrences[0].historicalKey='unknown-option';refreshRelease(r);assert.throws(()=>mapRelease(r),/occurrence_historical_key_invalid/);});
test('review2 corpus-wide key conflicts include excluded and media routes',()=>{for(const mode of ['excluded','media']){const r=makeRelease();r.records.questions.push(makeQuestion('test-q2',{stem:r.records.questions[0].app.stem,answerOptionId:'second'}));r.manifest.eligibility.includedIds.push('test-q2');if(mode==='excluded')r.records.questions[0].archive.gates[0].status='failed';else r.records.questions[0].app.classification.tasks=['image'];refreshRelease(r);assert.throws(()=>mapRelease(r),/answer_conflict/);}});
test('review3 differing explanations remain reviewable conflicts instead of lexical selection',()=>{const r=makeRelease();r.records.questions.push(makeQuestion('test-q2',{stem:r.records.questions[0].app.stem,explanation:'Different synthetic reasoning.'}));r.manifest.eligibility.includedIds.push('test-q2');refreshRelease(r);const h=packMapped(mapRelease(r));assert.equal(h.chunks.length,0);assert.ok(h.excluded.filter(x=>x.reason==='duplicate_content_conflict').length===2);assert.equal(h.state,'delivery_blocked');});
test('review4 existing version2 intelligence is validated against actual base and never rebound',()=>{const r=makeRelease(),t=targetFor(r),old=t.catalog.questions[0],v2={...structuredClone(old),questionVersionId:'test-q@2',version:2,supersedes:'test-q@1'};t.catalog.questions.push(v2);r.records.questions[0].app.intelligence={primaryTask:'recall',qualifiers:[],presentation:['one-line'],responseFormat:'single-best-answer',reasoningOperations:[],sourceQuestionVersionId:'test-q@2',derivatives:[]};t.questionMetadata[0].intelligence=structuredClone(r.records.questions[0].app.intelligence);r.records.questions[0].app.explanation+=' Changed';refreshRelease(r);validateCatalog(t.catalog);validateIntelligence(v2,r.records.questions[0].app.intelligence);const m=mapRelease(r,{target:t});assert.equal(m.routes[0].kind,'correction');assert.equal(m.routes[0].expectedVersionId,'test-q@2');assert.equal(r.records.questions[0].app.intelligence.sourceQuestionVersionId,'test-q@2');});
test('review5 unsupported existing question dependency yields scoped note exclusion not whole abort',()=>{const r=makeRelease(),t=targetFor(r);r.records.notes=[makeNote()];r.records.questions.push(makeQuestion('test-new'));r.manifest.eligibility.includedIds.push('test-note','test-new');r.records.relations=[{relationId:'test-link',kind:'explains',fromId:'test-note',toId:'test-q',section:''}];refreshRelease(r);const h=packMapped(mapRelease(r,{target:t}));assert.equal(h.chunks.length,1);assert.equal(h.chunks[0].manifest.questions[0].questionId,'test-new');assert.equal(h.chunks[0].manifest.notes.length,0);assert.ok(h.excluded.some(x=>x.recordId==='test-note'&&x.reason==='existing_question_dependency_requires_integration'));assert.equal(h.state,'delivery_blocked');});
test('review6 uncertain upload with empty lookup is not uploaded twice',async t=>{const {handoff,args}=await deliveryFixture(t),f=fakeArchive(),upload=f.port.upload;let first=true;f.port.upload=async x=>{const result=await upload(x);if(first){first=false;throw Error('uncertain');}return result;};const a=await archiveHandoff(handoff,{...args,...f});f.port.find=async()=>[];const b=await archiveHandoff(handoff,{...args,...f,priorReceipt:a});assert.equal(b.state,'persistence_pending');assert.equal(f.uploads,1);assert.equal(b.uncertainOperations.length,1);assert.equal(a.uncertainOperations[0].path,'release/manifest.json');});
test('review7 added verified exam source routes provenance and preserves source definitions',()=>{const r=makeRelease(),t=targetFor(r),s=structuredClone(r.records.sources[0]);s.recordId=s.app.sourceId='test-exam-source';s.app.version='exam-test-v1';r.records.sources.push(s);r.records.questions[0].app.sourceIds.push(s.recordId);addOccurrence(r,'first',s.recordId);const m=mapRelease(r,{target:t});assert.equal(m.routes[0].kind,'provenance');assert.deepEqual(t.catalog.sources.map(s=>s.sourceId),['test-source']);});
test('review8 any fixture evidence contributor prevents production archive receipt',async t=>{const release=makeRelease();Object.values(release.records).forEach(rows=>rows.forEach(row=>{if(row.archive)row.archive.fixture=false;}));refreshRelease(release);const {handoff,args}=await deliveryFixture(t,release),f=fakeArchive();f.port.fixture=false;const r=await archiveHandoff(handoff,{...args,...f});assert.equal(r.fixture,true);assert.throws(()=>validateArchiveReceipt(r,handoff),/fixture_receipt_rejected/);});

test('review6 upload intent must be saved before a possible external write',async t=>{const {handoff,args}=await deliveryFixture(t),f=fakeArchive();f.journal.append=async()=>{throw Error('journal failed');};const r=await archiveHandoff(handoff,{...args,...f});assert.equal(r.state,'persistence_pending');assert.equal(f.uploads,0);assert.equal(r.uncertainOperations.length,1);});
