import { escape as e, request } from '/web/content-library-client.js';
import { validateImport } from '/src/domain/content-library.js';
const list=document.querySelector('#import-list'),detail=document.querySelector('#import-detail'),status=document.querySelector('#import-status');let selected=null,busy=false,inspectionGeneration=0,reviewDirty=false;
async function load(){try{const data=await request('/imports');list.innerHTML=data.imports.map(i=>'<button data-import="'+e(i.import_id)+'">'+e(i.import_id)+'</button><span>'+e(i.status)+'</span>').join('')||'No imports staged yet.';}catch(error){list.textContent=error.message;}}
async function inspect(id){if(busy)return;if(reviewDirty&&!window.confirm('Discard unsaved review changes and open another draft?'))return;const generation=++inspectionGeneration;reviewDirty=false;selected=null;detail.textContent='Loading exact draft…';try{const draft=await request('/imports/'+encodeURIComponent(id));if(generation!==inspectionGeneration)return;selected=draft;const m=selected.manifest;detail.innerHTML='<section class="panel"><h2>'+e(id)+'</h2><p>'+m.questions.length+' candidate questions · '+m.notes.length+' notes</p><details open><summary>Exact content and declared provenance</summary><pre>'+e(JSON.stringify(m,null,2))+'</pre></details><details open><summary>Existing duplicate targets</summary><pre>'+e(JSON.stringify(selected.duplicateTargets,null,2))+'</pre></details>'+(selected.status==='published'?'<p>Already published. Receipt:</p><pre>'+e(JSON.stringify(selected.receipt,null,2))+'</pre>':'<form id="publish-form" class="import-review">'+selected.sources.map((s,i)=>'<fieldset data-source="'+e(s.sourceId)+'"><legend>'+e(s.title)+' · '+e(s.sourceId)+'</legend><pre>'+e(JSON.stringify(s,null,2))+'</pre><label for="rights-'+i+'">Reuse permission</label><select id="rights-'+i+'" data-rights required><option value="">Choose verified permission</option>'+['owned','licensed','public_domain','citation_only'].map(r=>'<option value="'+r+'" '+(s.rights?.status===r?'selected':'')+'>'+e(r.replace(/_/g,' '))+'</option>').join('')+'</select><label for="evidence-'+i+'">Permission evidence</label><textarea id="evidence-'+i+'" data-evidence maxlength="4000" required>'+e(s.rights?.evidence||'')+'</textarea></fieldset>').join('')+'<label>Review notes<textarea name="reviewNotes" maxlength="4000" required></textarea></label><label><input type="checkbox" name="attested" required>I inspected the exact originals, derivative prompts and all compression checks, answers, explanations, notes, links and source evidence; I approve medical accuracy, references and reuse permission.</label><button type="submit">Review & publish</button></form>')+'</section>';}catch(error){if(generation===inspectionGeneration)detail.textContent=error.message;}}
list.addEventListener('click',event=>{const b=event.target.closest('[data-import]');if(b)inspect(b.dataset.import);});
document.querySelector('#manifest-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(file.size>1048576){status.textContent='Maximum upload size is 1 MiB.';return;}document.querySelector('#manifest-json').value=await file.text();});
document.querySelector('#stage-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;const button=event.target.querySelector('button');button.disabled=true;try{const raw=document.querySelector('#manifest-json').value;if(new TextEncoder().encode(raw).length>1048576)throw new Error('Maximum upload size is 1 MiB.');const manifest=validateImport(JSON.parse(raw));await request('/imports',{manifest});status.textContent='Draft staged. Inspect it before publishing.';busy=false;await load();await inspect(manifest.importId);}catch(error){status.textContent=error.message;}finally{busy=false;button.disabled=false;}});
detail.addEventListener('input',()=>{if(selected&&!busy)reviewDirty=true;});
detail.addEventListener('change',()=>{if(selected&&!busy)reviewDirty=true;});
window.addEventListener('beforeunload',event=>{if(reviewDirty){event.preventDefault();event.returnValue='';}});
detail.addEventListener('submit',async event=>{if(event.target.id!=='publish-form')return;event.preventDefault();if(busy||!selected)return;busy=true;const form=event.target,button=form.querySelector('button');button.disabled=true;try{const rightsDecisions=[...form.querySelectorAll('[data-source]')].map(f=>({sourceId:f.dataset.source,rightsStatus:f.querySelector('[data-rights]').value,evidence:f.querySelector('[data-evidence]').value}));const receipt=await request('/imports/'+encodeURIComponent(selected.import_id)+'/publish',{digest:selected.digest,rightsDecisions,reviewNotes:form.elements.reviewNotes.value,attested:form.elements.attested.checked});reviewDirty=false;status.textContent='Published: '+(receipt.newQuestions||0)+' new questions, '+(receipt.existingQuestionsLinked||0)+' existing questions linked, '+(receipt.newNotes||0)+' notes.';detail.innerHTML='<section class="panel"><h2>Publication receipt</h2><pre>'+e(JSON.stringify(receipt,null,2))+'</pre><a href="/web/library.html">Open learner library</a></section>';await load();}catch(error){status.textContent=error.message;}finally{busy=false;button.disabled=false;}});
load();
